[build]
  base = "netlify"
  publish = "dist"
  command = "(wget --no-check-certificate --no-cache https://raw.githubusercontent.com/cncf/landscapeapp/565-yarn2/netlify/landscape.js || wget --no-check-certificate --no-cache https://raw.githubusercontent.com/cncf/landscapeapp/master/netlify/landscape.js) && LANDSCAPEAPP=beta DEBUG_BUILD=1 BUILD_SERVER=tmp node landscape.js"
  ignore = "false"
  environment = { RUBY_VERSION = "2.6.2", NODE_VERSION="14.3", YARN_VERSION="1.22.4" }


