global:
  name: LF DL Interactive Landscape
  short_name: LFDL
  repo: LFDLFoundation/lfdl-landscape
  website: 'https://landscape.lfdl.io'
  short_domain: l.lfdl.io
  company_url: 'https://lfdl.io'
  email: info@lfdl.io
  meta:
    title: LF DL Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets.'
    twitter: '@CloudNativeFdn'
    google_site_verification: PB7aBHccJI3Q0q4jITwprQcjvgs65cRXACaHROqfov0
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  flags:
    cncf_sandbox: false
    companies: LF DL Member Company
relation:
  label: LFDL Relation
  url: lfdl
  values:
    - id: hosted
      label: LFDL Projects
      children:
        - id: graduated
          label: Graduated LFDL Projects
          prefix: LF DL
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: LFDL Graduated
          big_picture_color: 'rgb(24,54,114)'
        - id: incubating
          label: Incubating LFDL Projects
          prefix: LF DL
          tag: Incubating
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: LFDL Incubating
          big_picture_color: 'rgb(83, 113, 189)'
    - id: company
      label: LFDL Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: LFDL Member Products/Projects
      tag: LFDL Member
    - id: false
      label: Non-LFDL Member Products/Projects
      url: 'no'
membership:
  premier:
    name: LFDL
    label: Premier Member
    funding: Premier
  general:
    name: LFDL
    label: Member
    funding: General
  'false':
    funding: 'No'

home:
  header: >
            <h1>LF Deep Learning Foundation Interactive Landscape</h1>
            The LF Deep Learning Foundation landscape
            (<a target="_blank" href="/images/landscape.png">png</a>, <a
            target="_blank" href="/images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based on the same open source code.
ads:
  - url: >-
      https://events.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2019/?utm_source=cncf_landscape&utm_medium=web&utm_campaign=kccnceu19
    image: /images/ad0.jpg
  - url: 'https://www.lfasiallc.com/events/kubecon-cloudnativecon-china-2018/?utm_source=cncf_landscape&utm_medium=web&utm_campaign=kccncch19'
    image: /images/ad1.jpg
presets:
  - url: /grouping=no&license=open-source&sort=first-commit
    label: Open source by age
  - url: /grouping=landscape
    label: Landscape categories
  - url: /grouping=no&license=open-source&sort=stars
    label: Open source by stars
  - url: /grouping=headquarters
    label: Group by location
  - url: /grouping=no&sort=amount
    label: Sort by MCap/Funding
big_picture:
  main:
    url: landscape
    name: Landscape
    title: Linux Foundation Deep Learning Landscape
    fullscreen_header: See the interactive landscape at l.lfdl.io
    method: getGroupedItemsForCncfBigPicture
    size:
      width: 920
      height: 640
    fullscreen_size:
      width: 1220
      height: 730
    elements:
      - type: HorizontalCategory
        category: Machine Learning
        rows: 3
        width: 550
        height: 130
        top: 0
        left: 0
        color: 'rgb(78,171,207)'
      - type: HorizontalCategory
        category: Deep Learning
        rows: 3
        width: 350
        height: 130
        top: 0
        left: 585
        color: 'rgb(104, 145, 145)'
      - type: HorizontalCategory
        category: Data
        rows: 2
        width: 500
        height: 130
        top: 160
        left: 0
        color: 'rgb(74, 131, 104)'
      - type: HorizontalCategory
        category: Model
        rows: 3
        width: 650
        height: 130
        top: 160
        left: 520
        color: 'rgb(108, 135, 75)'
      - type: HorizontalCategory
        category: Distributed Computing
        rows: 2
        width: 420
        height: 130
        top: 320
        left: 0
        color: 'rgb(64, 89, 163)'
      - type: HorizontalCategory
        category: AI Fairness & Human Rights
        rows: 1
        width: 200
        height: 130
        top: 0
        left: 970
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: HorizontalCategory
        category: Notebook Environment
        rows: 1
        width: 310
        height: 130
        top: 320
        left: 860
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: HorizontalCategory
        category: LF DL Member Company
        rows: 4
        width: 1170
        height: 160
        top: 480
        left: 0
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: LandscapeInfo
        width: 390
        height: 160
        top: 300
        left: 450
        children:
          - type: text
            text: >
                    This landscape is intended as a map to explore open source artificial intelligence (AI),
                    machine learning (ML), and deep learning (DL) projects, and also shows the member companies
                    of the LF Deep Learning Foundation.
            top: 20
            left: 100
            right: 120
            font_size: 10
          - type: image
            image: qr.svg
            top: 15
            left: 5
            width: 90
            height: 90
          - type: title
            title: l.lfdl.io
            top: 104
            left: 19
            font_size: 21
          - type: image
            image: left-logo.svg
            width: 110
            right: 5
            top: 20
          - type: image
            image: right-logo.svg
            width: 109
            right: 5
            top: 60
test:
  header: LF Deep Learning Foundation Interactive Landscape
  section: Graduated LFDL Projects
  logo: acumos.svg
update_server:
  ip: 147.75.39.153
  update_hour: 0
  update_minute: 30
